# Pseudo labeled data cleanup

## 1. Notebook setup
### 1.1. Imports

In [1]:
import pandas as pd

import configuration as config

### 1.2. Configuration

In [2]:
raw_data_path     = config.MERGED_CSV_PATH
cleaned_data_path = config.CLEANED_CSV_PATH

label_features = [
    'ACL','MCL','Medial Meniscus','Lateral Meniscus','Medial OA','Lateral OA',
    'PF OA','Effusion','Synovitis',"Baker's",'Contusion','Fracture'
]

## 2. Data inspection
### 2.1. Load pseudolabeled data

In [3]:
data = pd.read_csv(raw_data_path)
data = data[data['label_source'] != 'gold']
data = data[data['StudyInstanceUID'] != '1.2.826.0.1.3680043.8.498.12166235678892893545054546864889743251']
data = data[data['StudyInstanceUID'] != '1.2.826.0.1.3680043.8.498.91168270990167204047014161851340054645']

### 2.2. Inspect

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4347 entries, 58 to 4406
Data columns (total 40 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   StudyInstanceUID            4347 non-null   object
 1   Report                      0 non-null      object
 2   ACL                         4347 non-null   float64
 3   MCL                         4347 non-null   float64
 4   Medial Meniscus             4347 non-null   float64
 5   Lateral Meniscus            4347 non-null   float64
 6   Medial OA                   4347 non-null   float64
 7   Lateral OA                  4347 non-null   float64
 8   PF OA                       4347 non-null   float64
 9   Effusion                    4347 non-null   float64
 10  Synovitis                   4347 non-null   float64
 11  Baker's                     4347 non-null   float64
 12  Contusion                   4347 non-null   float64
 13  Fracture                    4347 non-null   float64
 14  label_source                4347 non-null   object
 15  ACL_agreement               4347 non-null   float64
 16  ACL_evidence                3872 non-null   object
 17  MCL_agreement               4347 non-null   float64
 18  MCL_evidence                3905 non-null   object
 19  Medial Meniscus_agreement   4347 non-null   float64
 20  Medial Meniscus_evidence    4097 non-null   object
 21  Lateral Meniscus_agreement  4347 non-null   float64
 22  Lateral Meniscus_evidence   3906 non-null   object
 23  Medial OA_agreement         4347 non-null   float64
 24  Medial OA_evidence          3251 non-null   object
 25  Lateral OA_agreement        4347 non-null   float64
 26  Lateral OA_evidence         2885 non-null   object
 27  PF OA_agreement             4347 non-null   float64
 28  PF OA_evidence              3127 non-null   object
 29  Effusion_agreement          4347 non-null   float64
 30  Effusion_evidence           3601 non-null   object
 31  Synovitis_agreement         4347 non-null   float64
 32  Synovitis_evidence          1515 non-null   object
 33  Baker's_agreement           4347 non-null   float64
 34  Baker's_evidence            2729 non-null   object
 35  Contusion_agreement         4347 non-null   float64
 36  Contusion_evidence          1276 non-null   object
 37  Fracture_agreement          4347 non-null   float64
 38  Fracture_evidence           1701 non-null   object
 39  pseudo_status               4347 non-null   object
dtypes: float64(24), object(16)
memory usage: 1.4+ MB

In [5]:
data.head().T

,58,59,60,61,62
StudyInstanceUID,1.2.826.0.1.3680043.8.498.10004873229099053869...,1.2.826.0.1.3680043.8.498.10004945927472656027...,1.2.826.0.1.3680043.8.498.10009278692606631573...,1.2.826.0.1.3680043.8.498.10009639203170750274...,1.2.826.0.1.3680043.8.498.10013663742400736029...
Report,NaN,NaN,NaN,NaN,NaN
ACL,0.0,0.0,0.0,0.0,0.0
MCL,0.0,0.0,0.0,0.0,1.0
Medial Meniscus,1.0,0.0,0.0,0.0,0.0
Lateral Meniscus,0.0,0.0,0.0,1.0,0.0
Medial OA,1.0,0.0,1.0,0.0,1.0
Lateral OA,0.0,0.0,0.0,0.0,1.0
PF OA,0.0,0.0,1.0,0.0,1.0
Effusion,1.0,0.0,0.0,0.0,0.0
Synovitis,0.0,0.0,0.0,0.0,0.0
Baker's,0.0,0.0,0.0,0.0,0.0
Contusion,0.0,0.0,0.0,0.0,0.0
Fracture,0.0,0.0,0.0,0.0,0.0
label_source,pseudo,pseudo,pseudo,pseudo,pseudo
ACL_agreement,1.0,1.0,1.0,1.0,1.0
ACL_evidence,NaN,NaN,Ligamentos cruzados y colaterales dentro de lí...,the anterior and posterior cruciate ligaments ...,Ligament croisé antérieur : Normal.
MCL_agreement,1.0,1.0,1.0,1.0,1.0
MCL_evidence,Rotura de menisco interno,NaN,Ligamentos cruzados y colaterales dentro de lí...,The medial collateral ligament complexes are i...,Ligament collatéral médial : Léger épaississem...
Medial Meniscus_agreement,1.0,1.0,1.0,1.0,1.0
Medial Meniscus_evidence,Rotura de menisco interno.,NaN,Aumento de señal del cuerno posterior del meni...,the meniscus is not torn,Ménisque médial : Légers changements dégénérat...
Lateral Meniscus_agreement,1.0,1.0,1.0,1.0,1.0
Lateral Meniscus_evidence,NaN,NaN,Menisco lateral de morfología y señal conserva...,suspicious incomplete discoid lateral meniscus...,Ménisque latéral : Normal.
Medial OA_agreement,1.0,1.0,1.0,1.0,1.0
Medial OA_evidence,Artrosis femorotibial medial.,NaN,Úlceras condrales de espesor parcial con fenóm...,there is no focal chondrosis or chondral injury,Changements dégénératifs : Chondropatie rétrop...
Lateral OA_agreement,1.0,1.0,1.0,1.0,1.0
Lateral OA_evidence,NaN,NaN,NaN,there is no focal chondrosis or chondral injury,Changements dégénératifs : Chondropatie légère...
PF OA_agreement,1.0,1.0,1.0,1.0,1.0
PF OA_evidence,NaN,NaN,Úlceras condrales espesor parcial de la rótula...,the patellar and trochlear cartilage appears c...,Chondropatie rétropatellaire modérée à sévère ...
Effusion_agreement,1.0,1.0,1.0,1.0,1.0
Effusion_evidence,. Derrame.,NaN,No hay evidente derrame articular ni quistes p...,No knee effusion is present,Épanchement articulaire : Pas de liquide signi...
Synovitis_agreement,1.0,1.0,1.0,1.0,1.0
Synovitis_evidence,NaN,NaN,NaN,NaN,Épanchement articulaire : Pas de liquide signi...
Baker's_agreement,1.0,1.0,1.0,1.0,1.0
Baker's_evidence,NaN,NaN,No hay evidente derrame articular ni quistes p...,NaN,Kyste de Baker : Aucun.
Contusion_agreement,1.0,1.0,1.0,1.0,1.0
Contusion_evidence,NaN,NaN,NaN,NaN,Signal de la moelle osseuse : Par ailleurs nor...
Fracture_agreement,1.0,1.0,1.0,1.0,1.0
Fracture_evidence,NaN,NaN,NaN,there is no fracture or bone contusion,Fractures : Aucune.
pseudo_status,pseudo,pseudo,pseudo,pseudo,pseudo

In [6]:
data.tail().T

,4402,4403,4404,4405,4406
StudyInstanceUID,1.2.826.0.1.3680043.8.498.99880021280666757817...,1.2.826.0.1.3680043.8.498.99881620336512626242...,1.2.826.0.1.3680043.8.498.99926624968240681772...,1.2.826.0.1.3680043.8.498.99939100657291954890...,1.2.826.0.1.3680043.8.498.99957611207313098696...
Report,NaN,NaN,NaN,NaN,NaN
ACL,0.0,1.0,0.0,0.0,0.0
MCL,0.0,0.0,0.0,0.0,0.0
Medial Meniscus,1.0,0.0,0.0,0.0,0.0
Lateral Meniscus,1.0,0.0,1.0,0.0,0.0
Medial OA,1.0,0.0,0.0,0.0,0.0
Lateral OA,1.0,0.0,0.0,0.0,0.0
PF OA,1.0,0.0,1.0,1.0,0.0
Effusion,1.0,0.0,1.0,1.0,0.0
Synovitis,1.0,0.0,1.0,0.0,0.0
Baker's,1.0,0.0,0.0,0.0,0.0
Contusion,0.0,1.0,0.0,0.0,0.0
Fracture,0.0,0.0,0.0,0.0,0.0
label_source,pseudo,pseudo,pseudo,pseudo,pseudo
ACL_agreement,1.0,1.0,1.0,1.0,1.0
ACL_evidence,There is mucoid degeneration of the anterior c...,Midsubstanti ële volledige voorste kruisbandru...,"Ön çapraz bağ ve arka çapraz bağ, ... normaldir.",The contour of ACL & PCL appear to be within n...,NaN
MCL_agreement,1.0,1.0,1.0,1.0,1.0
MCL_evidence,Medial collateral ligament (MCL): Normal.,verdere vermelding van intact mediaal collater...,"Ön çapraz bağ ve arka çapraz bağ, ... lateral ...",Both medial & lateral collateral ligaments app...,NaN
Medial Meniscus_agreement,1.0,1.0,0.666667,1.0,1.0
Medial Meniscus_evidence,Medial meniscus: There is a complex tear invol...,Normale configuratie signaalalteraties van de ...,Medial menisküste grade II dejenerasyon izlendi.,No strong MR evidence of tear is noted in eith...,NaN
Lateral Meniscus_agreement,1.0,1.0,1.0,1.0,1.0
Lateral Meniscus_evidence,Lateral meniscus: There is a complex tear invo...,Normale configuratie signaalalteraties van de ...,Lateral menisküste grade III dejenerasyon ve h...,No strong MR evidence of tear is noted in eith...,NaN
Medial OA_agreement,1.0,1.0,0.666667,1.0,1.0
Medial OA_evidence,Medial compartment cartilage: There is mild to...,NaN,medial menisküste grade II dejenerasyon izlendi,not explicitly mentioned,NaN
Lateral OA_agreement,1.0,0.666667,0.666667,1.0,1.0
Lateral OA_evidence,Lateral compartment cartilage: There is mild c...,NaN,lateral menisküste grade III dejenerasyon ve h...,not explicitly mentioned,NaN
PF OA_agreement,1.0,1.0,1.0,1.0,1.0
PF OA_evidence,mild to moderate cartilage thinning and fissur...,NaN,Patellar kıkırdakta yer yer hipointens değişik...,Heterogenous signal intensity of patellar cart...,NaN
Effusion_agreement,1.0,1.0,1.0,1.0,1.0
Effusion_evidence,"Small joint effusion. Mild, diffuse synovial p...",NaN,infrapatellar bursada sıvı artışı izlenmiştir,Some joint effusion,NaN
Synovitis_agreement,1.0,1.0,1.0,1.0,1.0
Synovitis_evidence,"Mild, diffuse synovial proliferation.",NaN,suprapatellar bursada hafif sıvı artışı izlendi,not explicitly mentioned,NaN
Baker's_agreement,1.0,1.0,1.0,1.0,1.0
Baker's_evidence,Moderate Baker cyst.,NaN,NaN,not explicitly mentioned,NaN
Contusion_agreement,1.0,1.0,1.0,1.0,1.0
Contusion_evidence,NaN,"""bone-bruise"" laesies lateraal tibiaplateau",NaN,No evidence of bone contusion is noted.,NaN
Fracture_agreement,1.0,1.0,1.0,1.0,1.0
Fracture_evidence,No acute fracture or bone bruise.,NaN,NaN,NaN,NaN
pseudo_status,pseudo,pseudo,pseudo,pseudo,pseudo

### 2.3. Label frequency

In [7]:
for label in label_features:
    display(data[label].value_counts())

ACL
0.0    3614
1.0     733
Name: count, dtype: int64

MCL
0.0    3949
1.0     398
Name: count, dtype: int64

Medial Meniscus
0.0    2389
1.0    1958
Name: count, dtype: int64

Lateral Meniscus
0.0    3578
1.0     769
Name: count, dtype: int64

Medial OA
0.0    3049
1.0    1298
Name: count, dtype: int64

Lateral OA
0.0    3713
1.0     634
Name: count, dtype: int64

PF OA
0.0    2737
1.0    1610
Name: count, dtype: int64

Effusion
1.0    2227
0.0    2120
Name: count, dtype: int64

Synovitis
0.0    3466
1.0     881
Name: count, dtype: int64

Baker's
0.0    3327
1.0    1020
Name: count, dtype: int64

Contusion
0.0    3889
1.0     458
Name: count, dtype: int64

Fracture
0.0    4097
1.0     250
Name: count, dtype: int64

In [8]:
mask = data[label_features].isin([1]).any(axis=1)
normal_scans = data[~mask]
print(f'Total normal scans: {len(normal_scans)}')

Total normal scans: 594

## 3. Set data types

In [9]:
int_features = [
    'ACL_agreement','MCL_agreement','Medial Meniscus_agreement','Lateral Meniscus_agreement',
    'Medial OA_agreement','Lateral OA_agreement','PF OA_agreement','Effusion_agreement',
    'Synovitis_agreement',"Baker's_agreement",'Contusion_agreement','Fracture_agreement'
]

int_features = int_features + label_features

['ACL_agreement',
 'MCL_agreement',
 'Medial Meniscus_agreement',
 'Lateral Meniscus_agreement',
 'Medial OA_agreement',
 'Lateral OA_agreement',
 'PF OA_agreement',
 'Effusion_agreement',
 'Synovitis_agreement',
 "Baker's_agreement",
 'Contusion_agreement',
 'Fracture_agreement',
 'ACL',
 'MCL',
 'Medial Meniscus',
 'Lateral Meniscus',
 'Medial OA',
 'Lateral OA',
 'PF OA',
 'Effusion',
 'Synovitis',
 "Baker's",
 'Contusion',
 'Fracture']

In [18]:
data[int_features] = data[int_features].astype(int)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4347 entries, 0 to 4346
Data columns (total 40 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   StudyInstanceUID            4347 non-null   object
 1   Report                      0 non-null      object
 2   ACL                         4347 non-null   int64
 3   MCL                         4347 non-null   int64
 4   Medial Meniscus             4347 non-null   int64
 5   Lateral Meniscus            4347 non-null   int64
 6   Medial OA                   4347 non-null   int64
 7   Lateral OA                  4347 non-null   int64
 8   PF OA                       4347 non-null   int64
 9   Effusion                    4347 non-null   int64
 10  Synovitis                   4347 non-null   int64
 11  Baker's                     4347 non-null   int64
 12  Contusion                   4347 non-null   int64
 13  Fracture                    4347 non-null   int64
 14  label_source                4347 non-null   object
 15  ACL_agreement               4347 non-null   int64
 16  ACL_evidence                3872 non-null   object
 17  MCL_agreement               4347 non-null   int64
 18  MCL_evidence                3905 non-null   object
 19  Medial Meniscus_agreement   4347 non-null   int64
 20  Medial Meniscus_evidence    4097 non-null   object
 21  Lateral Meniscus_agreement  4347 non-null   int64
 22  Lateral Meniscus_evidence   3906 non-null   object
 23  Medial OA_agreement         4347 non-null   int64
 24  Medial OA_evidence          3251 non-null   object
 25  Lateral OA_agreement        4347 non-null   int64
 26  Lateral OA_evidence         2885 non-null   object
 27  PF OA_agreement             4347 non-null   int64
 28  PF OA_evidence              3127 non-null   object
 29  Effusion_agreement          4347 non-null   int64
 30  Effusion_evidence           3601 non-null   object
 31  Synovitis_agreement         4347 non-null   int64
 32  Synovitis_evidence          1515 non-null   object
 33  Baker's_agreement           4347 non-null   int64
 34  Baker's_evidence            2729 non-null   object
 35  Contusion_agreement         4347 non-null   int64
 36  Contusion_evidence          1276 non-null   object
 37  Fracture_agreement          4347 non-null   int64
 38  Fracture_evidence           1701 non-null   object
 39  pseudo_status               4347 non-null   object
dtypes: int64(24), object(16)
memory usage: 1.3+ MB

## 4. Add reports

In [22]:
reports_df = pd.read_csv(config.TRAIN_CSV)
reports_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4407 entries, 0 to 4406
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   StudyInstanceUID  4407 non-null   object
 1   Report            4407 non-null   object
 2   ACL               58 non-null     float64
 3   MCL               58 non-null     float64
 4   Medial Meniscus   58 non-null     float64
 5   Lateral Meniscus  58 non-null     float64
 6   Medial OA         58 non-null     float64
 7   Lateral OA        58 non-null     float64
 8   PF OA             58 non-null     float64
 9   Effusion          58 non-null     float64
 10  Synovitis         58 non-null     float64
 11  Baker's           58 non-null     float64
 12  Contusion         58 non-null     float64
 13  Fracture          58 non-null     float64
dtypes: float64(12), object(2)
memory usage: 482.1+ KB

In [24]:
data['Report'] = reports_df['StudyInstanceUID'].map(reports_df.set_index('StudyInstanceUID')['Report'])

In [25]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4347 entries, 0 to 4346
Data columns (total 40 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   StudyInstanceUID            4347 non-null   object
 1   Report                      4347 non-null   object
 2   ACL                         4347 non-null   int64
 3   MCL                         4347 non-null   int64
 4   Medial Meniscus             4347 non-null   int64
 5   Lateral Meniscus            4347 non-null   int64
 6   Medial OA                   4347 non-null   int64
 7   Lateral OA                  4347 non-null   int64
 8   PF OA                       4347 non-null   int64
 9   Effusion                    4347 non-null   int64
 10  Synovitis                   4347 non-null   int64
 11  Baker's                     4347 non-null   int64
 12  Contusion                   4347 non-null   int64
 13  Fracture                    4347 non-null   int64
 14  label_source                4347 non-null   object
 15  ACL_agreement               4347 non-null   int64
 16  ACL_evidence                3872 non-null   object
 17  MCL_agreement               4347 non-null   int64
 18  MCL_evidence                3905 non-null   object
 19  Medial Meniscus_agreement   4347 non-null   int64
 20  Medial Meniscus_evidence    4097 non-null   object
 21  Lateral Meniscus_agreement  4347 non-null   int64
 22  Lateral Meniscus_evidence   3906 non-null   object
 23  Medial OA_agreement         4347 non-null   int64
 24  Medial OA_evidence          3251 non-null   object
 25  Lateral OA_agreement        4347 non-null   int64
 26  Lateral OA_evidence         2885 non-null   object
 27  PF OA_agreement             4347 non-null   int64
 28  PF OA_evidence              3127 non-null   object
 29  Effusion_agreement          4347 non-null   int64
 30  Effusion_evidence           3601 non-null   object
 31  Synovitis_agreement         4347 non-null   int64
 32  Synovitis_evidence          1515 non-null   object
 33  Baker's_agreement           4347 non-null   int64
 34  Baker's_evidence            2729 non-null   object
 35  Contusion_agreement         4347 non-null   int64
 36  Contusion_evidence          1276 non-null   object
 37  Fracture_agreement          4347 non-null   int64
 38  Fracture_evidence           1701 non-null   object
 39  pseudo_status               4347 non-null   object
dtypes: int64(24), object(16)
memory usage: 1.3+ MB

In [27]:
data.head(3).T

,0,1,2
StudyInstanceUID,1.2.826.0.1.3680043.8.498.10004873229099053869...,1.2.826.0.1.3680043.8.498.10004945927472656027...,1.2.826.0.1.3680043.8.498.10009278692606631573...
Report,Técnica: RMN de la rodilla. Resultados: Rotura...,[DATE]: * MR Knie Rechts 15ch AA Klinische Inl...,Hallazgos:\nNo hay alteraciones en significati...
ACL,0,0,0
MCL,0,0,0
Medial Meniscus,1,0,0
Lateral Meniscus,0,0,0
Medial OA,1,0,1
Lateral OA,0,0,0
PF OA,0,0,1
Effusion,1,0,0
Synovitis,0,0,0
Baker's,0,0,0
Contusion,0,0,0
Fracture,0,0,0
label_source,pseudo,pseudo,pseudo
ACL_agreement,1,1,1
ACL_evidence,NaN,NaN,Ligamentos cruzados y colaterales dentro de lí...
MCL_agreement,1,1,1
MCL_evidence,Rotura de menisco interno,NaN,Ligamentos cruzados y colaterales dentro de lí...
Medial Meniscus_agreement,1,1,1
Medial Meniscus_evidence,Rotura de menisco interno.,NaN,Aumento de señal del cuerno posterior del meni...
Lateral Meniscus_agreement,1,1,1
Lateral Meniscus_evidence,NaN,NaN,Menisco lateral de morfología y señal conserva...
Medial OA_agreement,1,1,1
Medial OA_evidence,Artrosis femorotibial medial.,NaN,Úlceras condrales de espesor parcial con fenóm...
Lateral OA_agreement,1,1,1
Lateral OA_evidence,NaN,NaN,NaN
PF OA_agreement,1,1,1
PF OA_evidence,NaN,NaN,Úlceras condrales espesor parcial de la rótula...
Effusion_agreement,1,1,1
Effusion_evidence,. Derrame.,NaN,No hay evidente derrame articular ni quistes p...
Synovitis_agreement,1,1,1
Synovitis_evidence,NaN,NaN,NaN
Baker's_agreement,1,1,1
Baker's_evidence,NaN,NaN,No hay evidente derrame articular ni quistes p...
Contusion_agreement,1,1,1
Contusion_evidence,NaN,NaN,NaN
Fracture_agreement,1,1,1
Fracture_evidence,NaN,NaN,NaN
pseudo_status,pseudo,pseudo,pseudo

## 5. Save cleaned data

In [29]:
data.to_csv(config.CLEANED_CSV_PATH, index=False)